### ISSUE TITLE
Data curation error caused by configuration files

### ISSUE THREAD

**Issue by solanoon** [tencent-ailab/DrugOOD#2]
Hello, I noticed that in some of the configuration python files of curators, there exist nested definitions of assay.

For example:

![image](https://user-images.githubusercontent.com/39321353/160882380-f03e051d-624f-4610-92cc-99353a9d0936.png)

After removing a layer of assay dictionary, the data curation process runs well.

**Comment by JiYuanFeng** [comment]
Hi! Thank you for informing us, we will fix these bugs.
